baseURL: "https://josedelapuente.com/"
languageCode: en-us
title: José de la Puente | Python and Platform engineering
theme: "PaperMod"
params:
  defaultTheme: dark
  description: "Software engineer specialized in Python internals, compilation and linking, distributed systems, and user experience design. Creator of the Horus observability system."
  disableThemeToggle: true
  hideFooter: true
  homeInfoParams:
    Content: |
      I'm a software engineer at [Thought Machine's](https://thoughtmachine.net) Developer Platform unit, where I'm focused on Python tooling, how our monorepo compiles and links, and improving the user experience of our tools.

      I also built [Horus](https://tryhorus.com), a full-stack observability system for distributed microservices.

      My current interests include:

      - How will technology reshape around voice as an interface? [Some hypotheses here](https://josedelapuente.com/posts/ais-iphone-moment/)
      - Python and Linux internals
      - Learning about biology and chemistry
  env: production
  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/josedlpuente"
    - name: "github"
      url: "https://github.com/14jdelap"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ja-puente/"
  label:
    text: "José de la Puente"
  isProduction: true
pygmentsOptions: "linenos=table"
