baseURL: "https://josedelapuente.com/"
languageCode: en-us
title: José de la Puente
theme: "PaperMod"
params:
  defaultTheme: dark
  disableThemeToggle: true
  hideFooter: true
  homeInfoParams:
    Content: |
      I'm a software engineer at [Thought Machine's](https://thoughtmachine.net) DevEx team, where I'm currently focused on working with our Please build system to compile C and Python. I've also worked on distributed systems (Go, gRPC and HTTP APIs, Postgres, Docker, K8s).

      I recently built [Horus](https://tryhorus.com), a full-stack observability system for distributed microservices.

  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/josedlpuente"
    - name: "github"
      url: "https://github.com/14jdelap"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ja-puente/"
  isProduction: true
pygmentsOptions: "linenos=table"
